In [1]:
import numpy as np

In [9]:
x = np.array(range(4))
print(x)
print(x.dtype)
print(x.size) # banyak item
print(x.ndim) # dimensi
print(x.itemsize)
print(x.shape)

[0 1 2 3]
int32
4
1
4
(4,)


In [24]:
a =  np.array([[1,2,3],
               [1,2,3]])
print(a.ndim)       # dimensi suatu matrix
print(a.shape)      # ukuran matrix misal (2x3)
print(a.size)       # banyaknya item dalam matrix dengan ukuran homogen penuh (tidak bolong)
print(x.itemsize)   # belum tahu

2
(2, 3)
6
4


## arange di Numpy sama seperti range() di python

In [30]:
print(np.arange(1,10,2))  # arange fungsinya sama seperti range di python
print(list(range(1,10,2)))

print(type(np.arange(1,10,2)))  # arange fungsinya sama seperti range di python
print(type(list(range(1,10,2))))

[1 3 5 7 9]
[1, 3, 5, 7, 9]
<class 'numpy.ndarray'>
<class 'list'>


## Numpy Random

In [53]:
print(np.random.random(10))   # menghasilkan angka random sebanyak 10 items (antara 0 - 1)

[ 0.63736964  0.08442043  0.6655813   0.07446925  0.05084458  0.20198844
  0.27418267  0.46852926  0.6584325   0.24043599]


In [57]:
print(np.random.rand(2,4)) # dengan menggunakan rand() kita bisa mendapatkan sejumlah matriks sesuai dengan ukuran yang kita param

[[ 0.46334839  0.8654293   0.52828358  0.92481387]
 [ 0.98160764  0.47496007  0.01170954  0.23479469]]


In [47]:
print(np.random.randint(7, size=10))      # randint() - menghasilkan angka integer, param 1 berupa batasan, size = jumlah 

[4 5 1 3 2 4 6 5 2 0]


In [51]:
print(np.random.randint(7, size=(3,2))) # size = (baris, kolom)

[[5 6]
 [4 6]
 [6 2]]


In [69]:
print(np.linspace(1,10,3))    # selisih tiap array sama

[  1.    5.5  10. ]


In [75]:
a = [(1,2,3), (4,5,6), (7,8,9), (10,11,12)]
a = np.array(a)

In [96]:
print(a[0,2])
print(a[ 0: , 0:2 ]) # selecting baris x hingga y menggunakan 'x:y'
print(a[ 0: , :1 ])
print(a[ 0: , 1 ])
print("------------------")
print(a[ [0,3] , 0: ]) # selecting bari x, baris y, baris z, gunakan index dalam '[x,y,z]'

3
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]
[[ 1]
 [ 4]
 [ 7]
 [10]]
[ 2  5  8 11]
------------------
[[ 1  2  3]
 [10 11 12]]


## Operasi Matriks

In [99]:
a = np.array([
    [0,-7],
    [-1,3]
])
b = np.array([
    [2,4],
    [3,8]
])

print(a+b)
print(a-b)
print(a+2) # setiap elemen a ditambah 2

[[ 2 -3]
 [ 2 11]]
[[ -2 -11]
 [ -4  -5]]
[[ 2 -5]
 [ 1  5]]


## LINEAR ALGEBRA

In [106]:
# 2x + y = 5
# x + y = 7
# SPLDV menggunakan numpy
# |2 1| |x| =  |5|
# |1 1| |y|    |7|

mat = np.array([[2,1], [1,1]])
hasMat = np.array([5,7])

hasil = np.linalg.solve(mat,hasMat)
print(hasil)

[-2.  9.]


In [109]:
# hasil = np.linalg.solve(np.array([3]), np.array([6]))

mat = np.array([[2,1,1], [1, 2, 1], [3, 2, 1]])
hasMat = np.array([4700, 4300, 7100])

hasil = np.linalg.solve(mat, hasMat)
print(hasil)

[ 1400.  1000.   900.]


In [138]:
#   def maks()
x = [1,4,3,5,2]
y =  np.array(x)
print(y)

from functools import reduce
print(np.sort(y))
z = np.sort(y)
print("max : ", z[-1])
print("min : ", z[0])
print("sum : ", reduce(lambda a,b : (a + b), z))

[1 4 3 5 2]
[1 2 3 4 5]
max :  5
min :  1
sum :  15
