In [2]:
import numpy as np

In [12]:
y = np.array([[1,2,1],[3,3,1],[2,1,2]])
print(y)
# ------------------------------------------------------------
print("determinanya : ", np.linalg.det(y))
(np.linalg.det(y))

[[1 2 1]
 [3 3 1]
 [2 1 2]]
determinanya :  -6.0


-6.0

In [22]:
x = [[3,2],[1,4]]
print("inversnya : ", np.linalg.inv(x))
invX =  np.linalg.inv(x)

# dot product 
print(x @ invX)

#cross product
print(x * invX)

print(np.__version__)

inversnya :  [[ 0.4 -0.2]
 [-0.1  0.3]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 1.2 -0.4]
 [-0.1  1.2]]


AttributeError: 'list' object has no attribute 'cross'

In [21]:
print(np.__version__)
array = np.arange(1,10)
print(array)

1.12.1
[1 2 3 4 5 6 7 8 9]
